spring:
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:mysql://localhost:3306/sakila
    username: username
    password: password
    driver-class-name: com.mysql.jdbc.Driver
